console.log('完成的第一个功能');
console.log('完成的第二个功能!!');
console.log('完成的第三个功能');
console.log('完成的第四个功能');
console.log('完成的第五个功能');
console.log('完成的第8个功能');
console.log('完成的第六个功能');
console.log('完成的第七个功能');
console.log('完成的第九个功能');